### ISSUE TITLE
using ::composer::config causes the resource to update every puppet run

### ISSUE THREAD

**Issue by agargiulo** [willdurand/puppet-composer#27]
### Description

using `::composer::config` causes the resource to update every puppet run

### Steps to reproduce

```puppet
  class { 'composer':
    user    => 'composer_user',
    require => User['composer_user'],
  }

  ::composer::config { 'composer-config':
    ensure  => present,
    user    => 'composer_user',
    configs => {
      'github-oauth' => {
        'github-server.example.com' => $deploy_key,
      },  
    },  
    require => Class['composer'],
  }
```
then
```shell
$> puppet agent -t
...
Info: Applying configuration version '1458917059'
...
Notice: /Stage[main]/Foo::Development/Composer::Config[composer-config]/Composer::Config::Entry['github-oauth'.'github-server.example.com'-composer_user-create]/Exec[composer-config-entry-'github-oauth'.'github-server.example.com'-composer_user-present]/returns: executed successfully
Notice: Finished catalog run in 5.58 seconds
```

### Expected behavior

This should only run when that config is changed manually outside of puppet, instead it runs evertime

### Further details
OS: Ubuntu 14.04
Puppet version 3.4.3
Facter version: 1.7.5
Version of this module is the master branch from git (642812a24aff418233ad6cfd138655c8b95f7a06 at the time of this issue being opened)

**Comment by Ma27** [comment]
at first thanks a lot for testing that stuff in master :)

well, I'mnot sure whether that's a "real" impact or an improvement. The thing is that puppet shouls IMHO "override everything" to make it compatible with the actual puppet config.
But if that's a bug for you, the next question is, hownto solve that?
We could attempt to create an even bigger "exec" that checks before applying the params, but then the exec would still be executed in your code. Facts aren't a good solution since these params are user dependent and loading stuff dynamically for getting the composer config and comparing them to the puppet one. This approach wouldn't save time, but makes the puppet process taking even more time.
If you have a well solution for that, PRs are welcome:)

**Comment by Ma27** [comment]
hmm ok after thinking a bit more about this I think it should be possible to do this using an 'unless' check.

**Comment by Ma27** [comment]
ok, fixed for now.
As you can read in the PR description, it isn't possible to check properly for config parameters that should be removed.

If this is an impact and someone really needs this feature, then please open a new ticket where we can discuss.
