### ISSUE TITLE
Duplicate declaration (wget) with willdurand/nodejs

### ISSUE THREAD

**Issue by cdoublev** [willdurand/puppet-composer#41]
### Description

Puppet fails to apply catalog. It outputs en error of a duplicate package (wget) declaration from init.pp, with willdurand/nodejs/manifests/instance/pkgs.pp (so both modules are using ensure_packages function from puppetlabs/stdlib).

### Steps to reproduce

Create Composer and NodeJS resources with willdurand/composer (1.2.2) and willdurand/nodejs (2.0.0-alpha1). Both require puppetlabs/stdlib >= 3.2.1 (version 4.14.0 was used).

### Further details

I managed to solve this issue by changing init.pp on line 53 from:

`ensure_packages(['wget'])` to `ensure_packages(['wget'], {ensure => 'installed'})`

... which I think is strange, as this second (optional) argument is always merged with `ensure => 'present'`, and I can read from Puppet docs that for the ensure attribute...

> Valid values are present (also called installed), absent, [...]

So obiously it should be a Puppet issue, but as I'm really not a Puppet expert, I prefered to open this issue and share this simple workaround.

**Comment by Ma27** [comment]
As we received tons of similar issues in `willdurand/puppet-nodejs`, I debugged the entire issue one time:
when using the `ensure_*` function it only avoids duplicated resources if each parameter of the resource is equal. As one of the modules uses an `ensure` parameter right now and the other one doesn't, Puppet crashes during the catalog evaluation.

The easiest fix would be to add `ensure => installed`. Care to open a PR?

**Comment by cdoublev** [comment]
Sorry I didn't search for this issue in `willdurand/puppet-nodejs`. I found [your comment](https://github.com/willdurand/puppet-nodejs/issues/168#issuecomment-259694816) explaining what's going on under `ensure_packages`.

I'm fine with opening your suggested PR, but would it not be better to remove any `ensure => installed` in `willdurand/puppet-nodejs` ? But I'm also fine with a local patch and wait for `ensure_*` functions to be eventually improved.

**Comment by Ma27** [comment]
> But I'm also fine with a local patch and wait for ensure_* functions to be eventually improved.

I don't think that this will ever happen. AFAIK this is the expected behavior (see the [docs](https://github.com/puppetlabs/puppetlabs-stdlib#ensure_resource) for reference).

I'd go for adding the `ensure => installed` parameter to the affected manifest in this module. Whenever you look at the [cookbook](https://www.puppetcookbook.com/posts/install-multiple-packages.html), the [official docs](https://docs.puppet.com/puppet/latest/types/package.html) or [the code](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/type/package.rb), you'll see that all code examples contain an `ensure` parameter when installing a new package.

If you'd like to open a PR for that, I'll have a look at it in the next days :)

**Comment by Ma27** [comment]
closed as of #42
